---
title: "Assignment: Module 2 - The LP Model Answer by Arvind Kumar Chaurasia"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

**LP Model: Question number 1**

Back Savers is a company that produces backpacks primarily for students. They are considering offering some combination of two different models—the Collegiate and the Mini. Both are made out of the same rip-resistant nylon fabric. Back Savers has a long- term contract with a supplier of the nylon and receives a 5000 square-foot shipment of the material each week. Each Collegiate requires 3 square feet while each Mini requires 2 square feet. The sales forecasts indicate that at most 1000 Collegiates and 1200 Minis can be sold per week. Each Collegiate requires 45 minutes of labor to produce and generates a unit profit of $32. Each Mini requires 40 minutes of labor and generates a unit profit of $24. Back Savers has 35 laborers that each provides 40 hours of labor per week. Management wishes to know what quantity of each type of backpack to produce per week.

a. Clearly define the decision variables
b. What is the objective function?
c. What are the constraints?
d. Write down the full mathematical formulation for this LP problem

**Answer to the question number 1**

Suppose, 

The number of Collegiate backpack $$ = b_c$$
The number of Mini backpack $$ = b_m$$


(a) Thus, the decision variables of the company are: 
$$ = b_c \hspace{.2cm}and\hspace{.2cm} b_m $$

(b) The objective function is to maximize the net profit which is the sum of the profits from Collegiate and Mini backpacks. So,
$$  Max \hspace{.2cm}  Z = 32b_c+24b_m$$
(c) Constraints:

Material Constraint: The total square footage of nylon fabric used should not exceed 5000 square feet per week.
 
 $$3b_c + 2b_m \le 5000   $$
Sales constraint: At most 1000 Collegiates and 1200 Minis backpacks can be sold per week. So, 
 
$$b_c \le 1000$$
$$b_m \le 1200$$

Labor-time constraint: Collegiate requires 45 minutes of labor to produce a unit and each Mini requires 40. Further, Back Savers has 35 laborers that each provides 40 hours of labor per week. Please note that we are also converting total working hour into minutes. So, 
 
 $$45b_c + 40b_m \le 60(35*40)$$
 
 (d) The complete LP model of the given question is then, 
 
$$Max \hspace{.2cm}  Z = 32b_c+24b_m$$
Subject to the following constraints: 

Material Constraint: 
$$3b_c + 2b_m \le 5000$$
Sales constraint: 
$$b_c \le 1000$$
$$b_m \le 1200$$

Labor-time constraint: 
$$45b_c + 40b_m \le 60(35*40)$$


And non-negativity of the decision variables: 
$$ b_c \ge 0, \hspace{.2cm} and \hspace{.2cm}b_m \ge 0$$
---


**LP Model: Question number 2**

The Weigelt Corporation has three branch plants with excess production capacity. Fortunately, the corporation has a new product ready to begin production, and all three plants have this capability, so some of the excess capacity can be used in this way. This product can be made in three sizes--large, medium, and small--that yield a net unit profit of $420, $360, and $300, respectively. Plants 1, 2, and 3 have the excess capacity to produce 750, 900, and 450 units per day of this product, respectively, regardless of the size or combination of sizes involved.

The amount of available in-process storage space also imposes a limitation on the production rates of the new product. Plants 1, 2, and 3 have 13,000, 12,000, and 5,000 square feet, respectively, of in-process storage space available for a day's production of this product. Each unit of the large, medium, and small sizes produced per day requires 20, 15, and 12 square feet, respectively.

Sales forecasts indicate that if available, 900, 1,200, and 750 units of the large, medium, and small sizes, respectively, would be sold per day.

At each plant, some employees will need to be laid off unless most of the plant’s excess production capacity can be used to produce the new product. To avoid layoffs if possible, management has decided that the plants should use the same percentage of their excess capacity to produce the new product.

Management wishes to know how much of each of the sizes should be produced by each of the plants to maximize profit. 

a. Define the decision variables 
b. Formulate a linear programming model for this problem.



**Answer to the question number 2**

Suppose, 

The number of large units produced per day at Plant 1 $$ = Lp_1$$
The number of medium units produced per day at Plant 1 $$ = Mp_1$$
The number of small units produced per day at Plant 1 $$ = Sp_1$$
The number of large units produced per day at Plant 2 $$ = Lp_2$$
The number of medium units produced per day at Plant 2 $$ = Mp_2$$
The number of small units produced per day at Plant 2 $$ = Sp_2$$
The number of large units produced per day at Plant 3 $$ = Lp_3$$
The number of medium units produced per day at Plant 3 $$ = Mp_3$$
The number of small units produced per day at Plant 3 $$ = Sp_3$$

(a) Thus, the decision variables of the company are:
$$ = Lp_1, Mp_1, Sp_1,Lp_2, Mp_2, Sp_2,Lp_3, Mp_3 \hspace{.2cm}and\hspace{.2cm} Sp_3$$

(b) LP Model for this problem:

The complete LP model of the given question is to maximize the profit, which is given by the following mathematical expression:

$$ Max \hspace{.2cm}  Z = 420(Lp_1 + Lp_2+ Lp_3) + 360(Mp_1+Mp_2+Mp_3) + 300(Sp_1 + Sp_2 +Sp_3 )$$

Subject to the following constraints: 

Production Capacity Constraints: Plants 1, 2, and 3 have the excess capacity to produce 750, 900, and 450 units per day of the product, respectively. Hence,
$$Lp_1 + Mp_1 + Sp_1 \le 750 $$
$$Lp_2 + Mp_2 + Sp_2 \le 900 $$
$$Lp_3 + Mp_3 + Sp_3 \le 450 $$
Sales forecast Constraints: Sales forecasts indicate that if available, 900, 1,200, and 750 units of the large, medium, and small sizes, respectively, would be sold per day. Hence,
$$Lp_1 + Lp_2 + Lp_3 \le 900 $$
$$Mp_1 + Mp_2 + Mp_3 \le 1200$$
$$Sp_1 + Sp_2 + Sp_3 \le 750$$
Storage Space Constraints: Plants 1, 2, and 3 have 13,000, 12,000, and 5,000 square feet, respectively, of in-process storage space available for a day's production of this product. Each unit of the large, medium, and small sizes produced per day requires 20, 15, and 12 square feet, respectively. Hence,

$$20Lp_1 + 15Mp_1 + 12Sp_1 \le 13000$$
$$20Lp_2 + 15Mp_2 + 12Sp_2 \le 12000 $$
$$20Lp_3 + 15Mp_3 + 12Sp_3 \le 5000$$
Equality constraints

The percentage of excess production capacity used at each plant can be calculated as follows:

Percentage of excess production capacity used = (Number of units produced)/(Excess production capacity)

Let's see one example, the percentage of excess production capacity used at Plant 1 will be calculated as follows:

$$ (Lp_1 + Mp_1 + Sp_1)/750 $$

Since, the percentage of excess production capacity used at each plant must be the same, the constraints would be,

$$ (Lp_1 + Mp_1 + Sp_1)/750 - (Lp_2 + Mp_2 + Sp_2)/900 = 0$$
$$ (Lp_1 + Mp_1 + Sp_1)/750 - (Lp_3 + Mp_3 + Sp_3)/450 = 0$$
And non-negativity of the decision variables: $$ Lp_1\ge 0, Mp_1\ge 0, Sp_1\ge 0,Lp_2\ge 0, Mp_2\ge 0, Sp_2\ge 0,Lp_3\ge 0, Mp_3\ge 0 \hspace{.2cm} and \hspace{.2cm} Sp_3 \ge 0$$

___


